#! /bin/bash

if [ "$EUID" == 0 ]
  then echo "Do not run this script as root"
  exit
fi

mkdir -p /home/ec2-user/logs
sudo -E env "PATH=$PATH" NODE_ENV=production forever start -a -o /home/ec2-user/logs/OUT -e /home/ec2-user/logs/ERR -l /home/ec2-user/logs/LOG app.js

